# Generated by Django 3.1.2 on 2020-10-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='fname',
            new_name='fisrt_name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='lname',
            new_name='last_name',
        ),
    ]
