# Generated by Django 3.1.2 on 2020-10-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201010_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='des_line1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='des_line2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='des_line3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='des_line4',
            field=models.CharField(default='', max_length=200),
        ),
    ]
