# Generated by Django 3.1.2 on 2020-10-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201010_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='des_line5',
            field=models.CharField(default='', max_length=200),
        ),
    ]
