# Generated by Django 3.1.2 on 2020-10-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_product_des_line5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='des_line1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='des_line2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='des_line3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='des_line4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='des_line5',
            field=models.CharField(default='', max_length=500),
        ),
    ]
